# AWS S3 Creds
AWS_S3_ACCESS_KEY_ID = ""
AWS_S3_SECRET_ACCESS_KEY = ""
AWS_S3_REGION = ""

# AWS Redshift Creds
AWS_REDSHIFT_CONN_URL = ""
AWS_REDSHIFT_DRIVER_PATH = ""
AWS_REDSHIFT_DRIVER = ""
AWS_REDSHIFT_USER = ""
AWS_REDSHIFT_PASSWORD = ""

